# Generated by Django 3.2.25 on 2025-11-07 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, default='Active', max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('register_number', models.CharField(blank=True, max_length=255, null=True)),
                ('commercial_code', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('logs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Our Company',
                'verbose_name_plural': 'Our Companies',
                'db_table': 'OurCompany',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='commercial_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='register_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
