# Generated by Django 3.2.25 on 2025-11-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20251107_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='stock_receipt_voucher_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipments',
            name='stock_receipt_voucher_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipments',
            name='stock_transfer_voucher_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipments',
            name='stock_transfer_voucher_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
