# Generated by Django 3.2.25 on 2025-11-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20251109_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipments',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
