# Generated by Django 3.2.25 on 2025-12-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20251110_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipments',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='stock_receipt_voucher_date',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='stock_receipt_voucher_number',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='stock_transfer_voucher_date',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='stock_transfer_voucher_number',
        ),
    ]
