# Generated by Django 3.2.25 on 2025-12-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20251203_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentProducts',
        ),
    ]
