# Generated by Django 3.2.25 on 2025-12-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_shipmentproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='commercial_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='register_number',
        ),
    ]
